# Example workflow for owo-reviewer
# Copy to .github/workflows/review.yml in your repo

name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  review:
    # Run on PR events, or on /review command in comments
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request &&
       contains(github.event.comment.body, '/review'))

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run owo-reviewer
        uses: jmagar/owo/packages/github-reviewer@main
        with:
          model: anthropic/claude-sonnet-4-5
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Or use other providers:
          # model: openai/gpt-4o
          # openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          #
          # model: opencode/glm-4-7
          # opencode_api_key: ${{ secrets.OPENCODE_API_KEY }}
