name: "owo-reviewer"
description: "AI-powered PR code review with inline comments"
branding:
  icon: "eye"
  color: "purple"

inputs:
  model:
    description: "Model to use in provider/model format (e.g., anthropic/claude-sonnet-4-5)"
    required: true

  github_token:
    description: "GitHub token for API access"
    required: true

  anthropic_api_key:
    description: "Anthropic API key (for Claude models)"
    required: false

  openai_api_key:
    description: "OpenAI API key (for GPT models)"
    required: false

  google_api_key:
    description: "Google API key (for Gemini models)"
    required: false

  opencode_api_key:
    description: "OpenCode API key (for OpenCode Zen models)"
    required: false

  reviewers:
    description: "JSON array of reviewer configs (optional)"
    required: false

  prompt:
    description: "Custom review prompt (optional)"
    required: false

  variant:
    description: "Model thinking level: low, default, high"
    required: false
    default: "default"

  use_github_token:
    description: "Use GITHUB_TOKEN directly instead of OpenCode App token exchange"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: "1.3.6"

    # TODO: Switch back to official opencode once SKIP_PULL_REQUEST_COMMENT is merged upstream
    # For now, build from jmagar's fork which has the feature

    - name: Clone and build opencode fork
      shell: bash
      run: |
        git clone --depth 1 --branch dev https://github.com/RawToast/opencode.git /tmp/opencode
        cd /tmp/opencode
        bun install
        ./packages/opencode/script/build.ts --single
        # Find the platform-specific binary
        mkdir -p ~/.opencode/bin
        cp ./packages/opencode/dist/opencode-*/bin/opencode ~/.opencode/bin/
        chmod +x ~/.opencode/bin/opencode

    - name: Add opencode to PATH
      shell: bash
      run: echo "$HOME/.opencode/bin" >> $GITHUB_PATH

    - name: Configure git identity
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install plugin dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        echo "Installing plugin dependencies at: $(pwd)"
        bun install --production
        ls -la

    - name: Set default prompt
      id: prompt
      shell: bash
      run: |
        if [ -n "${{ inputs.prompt }}" ]; then
          echo "value<<EOF" >> $GITHUB_OUTPUT
          echo "${{ inputs.prompt }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        else
          echo "value<<EOF" >> $GITHUB_OUTPUT
          cat << 'PROMPT_EOF' >> $GITHUB_OUTPUT
        You are a helpful code reviewer. Review this PR using the available tools:

        1. First, call get_pr_context() to get the PR diff and file changes
        2. Analyze the code for:
           - Bugs and potential issues
           - Security vulnerabilities
           - Code quality and best practices
           - Performance concerns
        3. Call submit_review() with:
           - A CodeRabbit-style overview (Summary, Changes table, Walkthrough)
           - Inline comments for specific issues (with file path and line number)

        Be constructive and helpful. Focus on actionable feedback.
        PROMPT_EOF
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - name: Run review
      shell: bash
      env:
        MODEL: ${{ inputs.model }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        GOOGLE_API_KEY: ${{ inputs.google_api_key }}
        OPENCODE_API_KEY: ${{ inputs.opencode_api_key }}
        REVIEWERS: ${{ inputs.reviewers }}
        VARIANT: ${{ inputs.variant }}
        USE_GITHUB_TOKEN: ${{ inputs.use_github_token }}
        PROMPT: ${{ steps.prompt.outputs.value }}
        # Pass config via env var to avoid creating opencode.json in repo (which would get committed)
        OPENCODE_CONFIG_CONTENT: '{"plugin": ["file://${{ github.action_path }}/src/index.ts"]}'
        # Skip the automatic PR comment since we post our own review via submit_review tool
        SKIP_PULL_REQUEST_COMMENT: "true"
      run: opencode github run
