#!/usr/bin/env bun
// packages/pr-review/src/index.ts

// Library exports
export { reviewPR, type ReviewOptions, type ReviewResult } from "./reviewer"
export * from "./github"
export * from "./ai"
export * from "./diff"
export * from "./config"
export * from "./reviewers"
export * from "./verifier"

import { writeFileSync } from "fs"
import { reviewPR, type ReviewOptions } from "./reviewer"
import { getPRContextFromEnv } from "./github/pr"
import { getGitHubToken } from "./github/client"
import type { Review } from "./github/types"

async function main() {
  const args = process.argv.slice(2)

  // Help
  if (args.includes("--help") || args.includes("-h")) {
    console.log(`
@owo/pr-review - AI-powered PR code review

Usage:
  owo-review [options]
  owo-review --pr <number> --owner <owner> --repo <repo>

Options:
  --pr <number>      PR number to review
  --owner <owner>    Repository owner
  --repo <repo>      Repository name
  --model <model>    Model to use (e.g., anthropic/claude-sonnet-4-20250514)
  --dry-run          Don't post review, just print it
  --output <file>    Save review to markdown file (implies --dry-run)
  --legacy           Use single-reviewer mode (original behavior)
  --help, -h         Show this help

Environment:
  GITHUB_TOKEN       Required. GitHub token with PR read/write access
  GITHUB_REPOSITORY  Optional. owner/repo format (auto-detected in Actions)
  GITHUB_EVENT_PATH  Optional. Path to event JSON (auto-set in Actions)

Examples:
  # In GitHub Actions (auto-detects PR context)
  owo-review

  # Manual review
  owo-review --pr 123 --owner myorg --repo myrepo

  # Dry run
  owo-review --pr 123 --owner myorg --repo myrepo --dry-run

  # Save to markdown file
  owo-review --pr 123 --owner myorg --repo myrepo --output review.md

  # Legacy single-reviewer mode
  owo-review --pr 123 --owner myorg --repo myrepo --legacy
`)
    process.exit(0)
  }

  // Parse args
  const getArg = (name: string): string | undefined => {
    const idx = args.indexOf(`--${name}`)
    return idx !== -1 ? args[idx + 1] : undefined
  }

  const prNumber = getArg("pr")
  const owner = getArg("owner")
  const repo = getArg("repo")
  const model = getArg("model")
  const outputFile = getArg("output")
  const dryRun = args.includes("--dry-run") || !!outputFile // --output implies dry-run
  const legacyMode = args.includes("--legacy")

  // Build options
  let options: ReviewOptions

  if (prNumber && owner && repo) {
    // Manual mode
    options = {
      token: getGitHubToken(),
      owner,
      repo,
      prNumber: parseInt(prNumber, 10),
      model,
      dryRun,
      legacyMode,
    }
  } else {
    // Auto-detect from GitHub Actions environment
    const ctx = getPRContextFromEnv()
    if (!ctx) {
      console.error("Error: Could not detect PR context.")
      console.error("Either run in GitHub Actions or provide --pr, --owner, --repo")
      process.exit(1)
    }

    options = {
      token: getGitHubToken(),
      owner: ctx.owner,
      repo: ctx.repo,
      prNumber: ctx.number,
      model,
      dryRun,
      legacyMode,
    }
  }

  console.log(`@owo/pr-review v0.2.0`)
  console.log(`Reviewing ${options.owner}/${options.repo}#${options.prNumber}`)
  if (legacyMode) {
    console.log(`Mode: legacy (single-reviewer)`)
  } else {
    console.log(`Mode: multi-reviewer`)
  }
  console.log("")

  const result = await reviewPR(options)

  if (!result.success) {
    console.error(`\nReview failed: ${result.error}`)
    process.exit(1)
  }

  if (dryRun && result.review) {
    if (outputFile) {
      // Save full review to markdown file
      const markdown = formatReviewAsMarkdown(result.review, options)
      writeFileSync(outputFile, markdown)
      console.log(`\nReview saved to: ${outputFile}`)
      console.log(`  Overview + ${result.review.comments.length} inline comments`)
    } else {
      // Print to console
      console.log("\n--- Review (dry run) ---")
      console.log(result.review.overview)
      console.log(`\nInline comments: ${result.review.comments.length}`)
      for (const c of result.review.comments) {
        console.log(`  ${c.path}:${c.line} - ${c.body.slice(0, 50)}...`)
      }
    }
  } else {
    console.log(`\nReview ${result.isUpdate ? "updated" : "posted"}: ${result.reviewUrl}`)
  }
}

/**
 * Format a review as a complete markdown document
 */
function formatReviewAsMarkdown(review: Review, options: ReviewOptions): string {
  const lines: string[] = []

  // Header
  lines.push(`# PR Review: ${options.owner}/${options.repo}#${options.prNumber}`)
  lines.push("")
  lines.push(`*Generated by [owo-pr-review](https://github.com/RawToast/owo)*`)
  lines.push("")
  lines.push("---")
  lines.push("")

  // Main overview (already formatted by verifier)
  lines.push(review.overview)
  lines.push("")

  // Inline comments section
  if (review.comments.length > 0) {
    lines.push("---")
    lines.push("")
    lines.push("## Inline Comments")
    lines.push("")
    lines.push(`*${review.comments.length} comments to be posted as inline review comments:*`)
    lines.push("")

    for (const comment of review.comments) {
      lines.push(`### \`${comment.path}:${comment.line}\``)
      lines.push("")
      lines.push(comment.body)
      lines.push("")
      lines.push("---")
      lines.push("")
    }
  }

  return lines.join("\n")
}

main().catch((err) => {
  console.error("Fatal error:", err)
  process.exit(1)
})
